package ga.lupuss.anotherbikeapp

enum class Message {
    ACCOUNT_CREATED,
    USER_EXISTS,
    SOMETHING_GOES_WRONG,
    FILL_ALL_FIELDS,
    NO_INTERNET_CONNECTION,
    EMAIL_OR_PASSWORD_BLANK,
    INCORRECT_CREDENTIALS,
    NO_PERMISSION,
    LOCATION_NOT_AVAILABLE,
    USER_NOT_EXISTS
}

enum class AppTheme {
    GREY, ORANGE
}

enum class Text {
    DEFAULT_ROUTE_NAME
}